### Project Overview 
**Objective:** 
- Determine which laptop would bring the most bang for the least buck. 

**Data Source:** Describe where the data comes from and how it might answer the question.
- https://www.kaggle.com/datasets/krishnandansah/laptop-data

### Data Collection and Loading 
- **Load Data:** Use Pandas to load a dataset (CSV, Excel, or database).
- **Initial Check:** Display the first few rows and basic information about the dataset, noting column names, types, and missing values.
- **Selection Options:**
    - Choose a dataset you find interesting (Video game sales, Sports stats, Carbon emissions, etc.).
    - Choose which columns or data to focus on and drop the rest.

### IMPORT PANDAS, MATPLOTLIB, & MONEYPANDAS

In [1]:
#Loading pandas and matplotlib
#ADDED To V2 less moneypandas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import moneypandas as mp

### DATA LOAD

In [2]:
#Loading dataset
#ADDED to V2
laptop_data = pd.read_csv("laptopData.csv")

### INITIAL CHECKS
- Dataframe Info
- Dataframe Header Rows
- Dataframe Tail Rows
- Dataframe Duplicate Rows Count
- Dataframe Missing Values

In [3]:
#Dispaly information about the dataset (i.e., row counts, column counts, column names, datatypes, # of non-null rows)
#ADDED to V2
laptop_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   object
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   Ram               1273 non-null   object
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight            1273 non-null   object
 11  Price             1273 non-null   float64
dtypes: float64(2), object(10)
memory usage: 122.3+ KB

In [4]:
#Dispaly the first 5 header rows
#ADDED to V2
laptop_data.head(5)

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [5]:
#Display the last 5 rows
#ADDED to V2
laptop_data.tail(5)

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
1298,1298.0,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.64
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.72
1300,1300.0,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.12
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.92
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.32

In [6]:
#Displays duplicated rows value count true/false
#ADDED to V2
laptop_data.duplicated().value_counts()

False    1274
True       29
Name: count, dtype: int64

In [7]:
#Describes the numerical columns and returns a statistcal description of each 
# NEED TO ADD
laptop_data.describe()

        Unnamed: 0          Price
count  1273.000000    1273.000000
mean    652.674784   59955.814073
std     376.493027   37332.251005
min       0.000000    9270.720000
25%     327.000000   31914.720000
50%     652.000000   52161.120000
75%     980.000000   79333.387200
max    1302.000000  324954.720000

In [8]:
# Select_dtypes() filters columns based on specified data type, in my case "Objects" since the rest of my columns contain strings, within the df.  
# Describe() returns a statistical description of the specified data types in the df including total count, unique values in each column, the top value in each column and its frequency
# Added to Initial Checks section V2
# NEED to ADD to statistical analysis section
laptop_data.select_dtypes("object").describe()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
count,1273,1273,1273,1273,1273,1273,1273,1273,1273,1273
unique,19,6,25,40,118,10,40,110,9,189
top,Lenovo,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,2.2kg
freq,290,710,640,495,183,601,401,271,1047,111

In [10]:
#Boolean output confirming if there are any rows with null values
laptop_data.isnull().values.any()
#Output should be 'np.True_'

np.True_

In [11]:
#Row count of null data 
laptop_data.isnull().any(axis=1).sum()

np.int64(30)

In [12]:
#Displays only rows with Null values
laptop_data[laptop_data.isna().any(axis=1)]

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Data Cleaning and Preparation 
- **Handle Missing Values:** Choose how to handle missing values (drop, fill, or leave as is).
    - There were no null values in this dataset 
- **Data Type Adjustments:** Convert columns to appropriate types (e.g., dates to datetime).
- **Feature Engineering:** Create at least one new feature from existing data.
    - Example: extracting the month from a date
    - Calculate the percentage
    - Combine first and last name columns into a full name column

In [13]:
#ADDED to V2
#Cleaning Data - Drop duplicate rows 
laptop_data_deduped = laptop_data.drop_duplicates()
display(laptop_data_deduped)

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298.0,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300.0,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [14]:
#ADDED to V2
#counts the total number of "?" (or question marks [qm] by column 
qm_counts = (laptop_data_deduped == "?").sum()
#sums the total number of qms in the df
total_qms = qm_counts.sum()
print("Counts of '?' by column: ") 
print(qm_counts)
print()
print(f"Total count of '?' in the df: {total_qms}.")

Counts of '?' by column:
Unnamed: 0          0
Company             0
TypeName            0
Inches              1
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              1
Gpu                 0
OpSys               0
Weight              1
Price               0
dtype: int64

Total count of '?' in the df: 3.

In [15]:
#ADDED to V2
#Identify index # of row with "?" to use for dropping these rows in future code
questmark1 = laptop_data_deduped[laptop_data_deduped.Inches == "?"]
questmark2 = laptop_data_deduped[laptop_data_deduped.Memory == "?"]
questmark3 = laptop_data_deduped[laptop_data_deduped.Weight == "?"]
print(questmark1.index)
print(questmark2.index)
print(questmark3.index)

Index([476], dtype='int64')
Index([770], dtype='int64')
Index([208], dtype='int64')

In [16]:
#drop rows with incomplete data (a.k.a. rows containing "?" in place of column value)
laptop_data_drop_rows = laptop_data_deduped.drop(labels = [208, 476, 770], axis = 0)
laptop_data_drop_rows

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298.0,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300.0,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [ ]:
# ADDED to to Data Type Adjusments V2
laptop_data_drop_rows["Weight"] = laptop_data_drop_rows["Weight"].str.replace("kg","")
laptop_data_drop_rows.head(5)

In [ ]:
# Added to Data Type Adjusments V2
laptop_data_drop_rows[["Weight","Inches"]]=laptop_data_drop_rows[["Weight","Inches"]].astype(float)
laptop_data_drop_rows.head(5) #removed this line

In [ ]:
# Added to line above in Data Type Adjustments V2 as check
laptop_data_drop_rows.info()

In [ ]:
#Added to V2
#Cleaning Data - Drop Columns & display column info to ensure correct column dropped
laptop_data_deduped_dropcol = laptop_data_drop_rows.drop("Unnamed: 0",axis=1)
laptop_data_deduped_dropcol.columns

In [ ]:
#Cleaning Data - Update price column name to 'Price_RUP', round 'Price_RUP' column to 2 decimals & display column info to ensure correct column renamed
#Added to V2 plus several other columns
laptop_data_deduped_dropcol.rename(columns={"Price": "Price_RUP"}, inplace=True)
laptop_data_deduped_dropcol.columns

In [ ]:
#Cleaning Data - Round "Price_Rub" column to two decimal places & Display top rows to ensure correct formatting
laptop_data_prices = laptop_data_deduped_dropcol.round({"Price_RUP":2})
laptop_data_prices.head()

In [ ]:
#Cleaning Data - Add a new price column converting RUP to USD using latest exchange rate of $1 to 0.12 RUP as of 12/05/2024 and name new column 'Price_USD'
laptop_data_prices["Price_USD"] = (laptop_data_prices["Price_RUP"] * 0.012).round(2)
laptop_data_prices.head()

In [ ]:
laptop_data_cleaned["Ram"].unique()

### Exploratory Data Analysis (EDA) 
- **Descriptive Statistics:** Provide summary statistics (mean, median, min, max) for numerical columns.
Data Visualizations:
    - **Required:** One visualization (e.g., line plot) if time-series data is relevant.
    - **Optional:** Additional visuals like bar charts for comparisons, histograms for distributions, or scatter plots for relationships.

### Analysis and Insights
- **Findings:** Summarize any patterns observed and address the main project question.
- **Supporting Data:** Reference specific statistics or plot features to back up findings.

### Conclusion and Recommendations
- **Summarize:** Present the main conclusions drawn from the analysis.
- **Recommendations:** Based on findings, suggest actions or further analysis.

### Optional Advanced Section (Bonus)
- **Advanced EDA:** Use pair plots or correlation matrices to explore relationships.
- **Dashboards:** Create a simple dashboard with Matplotlib or extend to Dash/Streamlit.